export enum ICON {
  MENU = "heroicons-outline:menu-alt-3",
  FLARE = "ic:round-flare",
  CANCEL = "hugeicons:cancel-01",

TAILWIND = "devicon:tailwindcss",
  ASTRO = "material-icon-theme:astro",
  REACT = "material-icon-theme:react",
  PYTHON = "material-icon-theme:python",
  TYPESCRIPT = "skill-icons:typescript",
  JAVASCRIPT = "skill-icons:javascript",
  NEXTJS = "devicon:nextjs",
  ANGULAR = "devicon:angular",
  GSAP = "simple-icons:gsap",
  FRAMER_MOTION = "tabler:brand-framer-motion",
  SCSS = "vscode-icons:file-type-scss",
  SUPABASE = "devicon:supabase",
  FIREBASE = "devicon:firebase",
  CYPRESS = "material-icon-theme:cypress",
  JEST = "material-icon-theme:jest",
  VITEST = "simple-icons:vitest",
  GIT="devicon:git",
  REACT_QUERY="simple-icons:reactquery",
  GITHUB_ACTIONS="devicon:githubactions",
  BOOTSTRAP="devicon:bootstrap",
  ZUSTAND="devicon:zustand",
  REDUX="devicon:redux",
  VERCEL="skill-icons:vercel-light",
  NETLIFY="material-icon-theme:netlify",
  THREE="skill-icons:threejs-light",
  NODE="devicon:nodejs",
}
